// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/zhanbo/happy/x-render/docs/chart-render/0.1.X/demo/pivot-table.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/zhanbo/happy/x-render/docs/chart-render/0.1.X/demo/column.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/zhanbo/happy/x-render/docs/form-render/example-frequently.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/zhanbo/happy/x-render/docs/form-render/advanced-validate.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/zhanbo/happy/x-render/docs/chart-render/0.1.X/demo/line.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/zhanbo/happy/x-render/docs/form-render/advanced-linkage.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/zhanbo/happy/x-render/docs/form-render/advanced-layout.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/zhanbo/happy/x-render/docs/form-render/advanced-widget.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/zhanbo/happy/x-render/docs/chart-render/widget/custom.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/zhanbo/happy/x-render/docs/form-render/disaply-column.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/zhanbo/happy/x-render/docs/form-render/advanced-path.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/zhanbo/happy/x-render/docs/chart-render/0.1.X/index.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/zhanbo/happy/x-render/docs/chart-render/widget/line.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/zhanbo/happy/x-render/docs/form-render/disaply-row.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/zhanbo/happy/x-render/docs/chart-render/0.1.X/faq.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/zhanbo/happy/x-render/docs/form-render/api-schema.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/zhanbo/happy/x-render/docs/form-render/api-props.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/zhanbo/happy/x-render/docs/form-render/changelog.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/zhanbo/happy/x-render/docs/tools/proptypes/index.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/zhanbo/happy/x-render/docs/generator/playground.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/zhanbo/happy/x-render/docs/table-render/migrate.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/zhanbo/happy/x-render/docs/form-render/migrate.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/zhanbo/happy/x-render/docs/chart-render/index.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/zhanbo/happy/x-render/docs/table-render/index.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/zhanbo/happy/x-render/docs/tools/vscode/index.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/zhanbo/happy/x-render/docs/chart-render/demo.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/zhanbo/happy/x-render/docs/form-render/index.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/zhanbo/happy/x-render/docs/table-render/demo.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/zhanbo/happy/x-render/docs/chart-render/faq.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/zhanbo/happy/x-render/docs/playground/index.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/zhanbo/happy/x-render/docs/table-render/api.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/zhanbo/happy/x-render/docs/form-render/faq.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/zhanbo/happy/x-render/docs/generator/index.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/zhanbo/happy/x-render/docs/generator/demo.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/zhanbo/happy/x-render/docs/generator/faq.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/zhanbo/happy/x-render/docs/index.en-US.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/zhanbo/happy/x-render/docs/index.zh-CN.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/chart-render/0.1.X/demo/pivot-table': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/chart-render/0.1.X/demo/column': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/form-render/example-frequently': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/form-render/advanced-validate': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/chart-render/0.1.X/demo/line': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/form-render/advanced-linkage': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/form-render/advanced-layout': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/form-render/advanced-widget': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/chart-render/widget/custom': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/form-render/disaply-column': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/form-render/advanced-path': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/chart-render/0.1.X/index': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/chart-render/widget/line': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/form-render/disaply-row': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/chart-render/0.1.X/faq': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/form-render/api-schema': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/form-render/api-props': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/form-render/changelog': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/tools/proptypes/index': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/generator/playground': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/table-render/migrate': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/form-render/migrate': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/chart-render/index': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/table-render/index': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/tools/vscode/index': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/chart-render/demo': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/form-render/index': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/table-render/demo': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/chart-render/faq': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/playground/index': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/table-render/api': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'docs/form-render/faq': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/generator/index': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'docs/generator/demo': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/generator/faq': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/index.en-US': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'docs/index.zh-CN': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
