// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhanbo/happy/x-render/node_modules/dumi/theme-default/slots/SocialIcon/index.js';
